Initial instructions on filing HST quaterly
hyphacoop/handbook pull request #142
Opened 2021-09-23 17:08 UTC by YurkoWasHere

Instructions on how to prepare, file and pay HST quarterly

2021-09-23 17:09 UTC, YurkoWasHere commented on guides.md
> +- [Reporting HST]
Not sure how this works:

```suggestion
- [Reporting HST](#reporting-hst)
```

2021-09-23 17:09 UTC, benhylau commented on guides.md
> +- [Reporting HST]
```suggestion
- [Reporting HST](#reporting-hst)
```

2021-09-23 17:09 UTC, YurkoWasHere commented on guides.md
> +14. Click `File`
Need to confirm the text on this button

2021-09-23 17:10 UTC, YurkoWasHere commented on guides.md
> +If payment is required for HST, you will need to coordinate with another member that has signing authority at the bank. The payment must be confirmed by the 2nd person within 24 hours.
I think it may be 48  hours not 24?

2021-09-23 17:11 UTC, benhylau commented on guides.md
> +11. Review summary, and check line `109` and `114` or `115` for matching values from the bookkeer's email
```suggestion
11. Review summary, and check line `109` and `114` or `115` for matching values from the bookkeeper's email
```

2021-09-23 17:12 UTC, benhylau commented on guides.md
> +17. Uplod file to Googe Drive until `Finance/HST`
```suggestion
17. Upload file to Google Drive until `Finance/HST`
```

2021-09-23 17:13 UTC, benhylau commented on guides.md
> +9. Select `next`
```suggestion
9. Select `Next`
```

2021-09-23 17:14 UTC, benhylau commented on guides.md
> +- [ ] Step 14 of filling - confirm name of button
Get rid of this before merge.

2021-09-23 17:14 UTC, benhylau requested changes
Can merge after my comments.

2022-04-12 14:05 UTC, YurkoWasHere commented on guides.md
> +If payment is required for HST, you will need to coordinate with another member that has signing authority at the bank. The payment must be confirmed by the 2nd person within 24 hours.
```suggestion
If payment is required for HST, you will need to coordinate with another member that has signing authority at the bank. The payment must be confirmed by the 2nd person within 48 hours.
```

2022-04-12 14:05 UTC, YurkoWasHere commented on guides.md
> +If payment is required for HST, you will need to coordinate with another member that has signing authority at the bank. The payment must be confirmed by the 2nd person within 24 hours.
Good to merge just a small change 24->48 hours

2022-04-23 15:56 UTC, YurkoWasHere commented
Gdod tho merge

2022-04-25 04:27 UTC, benhylau commented on guides.md
>  - [Initatives](#initatives)
```suggestion
- [Initiatives](#initiatives)
```

2022-04-25 04:27 UTC, benhylau commented on guides.md
>  ## Initatives
```suggestion
## Initiatives
```

2022-04-25 04:28 UTC, benhylau approved these changes

2022-04-25 04:30 UTC, merged