added in step by step of local editing process
hyphacoop/handbook pull request #176
Opened 2022-04-22 16:21 UTC by writerly03

Hope these steps are clear enough; this is the process if using GH Desktop so not sure if more explanation is required if not using this interface

2022-04-23 02:34 UTC, uditvira requested changes
Added instructions for command line as well

2022-04-23 02:34 UTC, uditvira commented on README.md
> +1. Check that your local version of the main (master) is up to date
```suggestion
1. Check that your local version of the main (master) branch is up to date. If not, you should pull recent changes from GitHub. On the command line you'll have to first use `git checkout master` and then `git pull`.
```

2022-04-23 02:34 UTC, uditvira commented on README.md
> +2. Create a new branch: select New branch (if using GitHub Desktop) and give it a title of whatever you're planning to work on e.g. roles-page-update
```suggestion
2. Create a new branch: select New branch (if using GitHub Desktop) and give it a title of whatever you're planning to work on e.g., roles-page-update. On the command line you can use `git checkout -b your-branch-name`.
```

2022-04-23 02:34 UTC, uditvira commented on README.md
> +4. Write a summary of the changes
```suggestion
4. If you're using the command line, you'll have to stage changes you want to commit. You can use `git add file-name` to do that.
```

2022-04-23 02:34 UTC, uditvira commented on README.md
> +5. Commit the change
```suggestion
5. Commit the change and write a summary message for that commit. If using the command line, you can use `git commit -m "your summary message"
```

2022-04-23 02:34 UTC, uditvira commented on README.md
> +6. Make a pull request to the main
```suggestion
6. Push the changes upstream to GitHub. With the command line you can use `git push`
7. Make a pull request to the master branch from your branch
```

2022-04-23 02:34 UTC, uditvira commented on README.md
> +7. Assign a co-worker to review the changes
If you accept my other suggestions you'll have to change the numbering
```suggestion
8. Assign a co-worker to review the changes
```

2022-04-23 02:34 UTC, uditvira commented on README.md
> +8. Co-worker reviews and then accepts the pull request, and the update is made
ibid
```suggestion
9. Co-worker reviews and then accepts the pull request, and the update is made  
```

2022-11-29 21:14 UTC, tripledoublev approved these changes

2022-11-29 21:16 UTC, tripledoublev approved these changes

2022-11-29 21:17 UTC, merged